telegram-token = ${APP_TELEGRAM_TOKEN}
environment = ${?ENV}
logs-file = ${?LOGS_FILE}
updates-interval-seconds = 60
bot-url = ${BOT_URL}
scrapper-url = ${SCRAPPER_URL}
bot-api-port = ${BOT_API_PORT}
scrapper-api-port = ${SCRAPPER_API_PORT}
api-protocol = grpc
api-protocol = ${?API_PROTOCOL}