services:
  bot:
    build:
      context: .
      dockerfile: cmd/bot/Dockerfile
    ports:
      - "${API_BOT_SERVER_PORT:-63342}:63342" # это только на время, потом не нужно будет это показывать, тк микросервисы все будут в одной сети
    env_file:
      - .env
    depends_on:
      - scrapper
    environment:
      - SCRAPPER_URL=http://scrapper:63343

  scrapper:
    build:
      context: .
      dockerfile: cmd/scrapper/Dockerfile
    ports:
      - "${API_SCRAPPER_SERVER_PORT:-63343}:63343"
    env_file:
      - .env
    environment:
      - BOT_URL=http://bot:63342