// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: docs/scrapper.proto

package scrapper

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterChatRequest) Reset() {
	*x = RegisterChatRequest{}
	mi := &file_docs_scrapper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterChatRequest) ProtoMessage() {}

func (x *RegisterChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_scrapper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterChatRequest.ProtoReflect.Descriptor instead.
func (*RegisterChatRequest) Descriptor() ([]byte, []int) {
	return file_docs_scrapper_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterChatRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChatRequest) Reset() {
	*x = DeleteChatRequest{}
	mi := &file_docs_scrapper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChatRequest) ProtoMessage() {}

func (x *DeleteChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_scrapper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChatRequest.ProtoReflect.Descriptor instead.
func (*DeleteChatRequest) Descriptor() ([]byte, []int) {
	return file_docs_scrapper_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteChatRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetLinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TgChatId      int64                  `protobuf:"varint,1,opt,name=tg_chat_id,json=tgChatId,proto3" json:"tg_chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLinksRequest) Reset() {
	*x = GetLinksRequest{}
	mi := &file_docs_scrapper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinksRequest) ProtoMessage() {}

func (x *GetLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_scrapper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinksRequest.ProtoReflect.Descriptor instead.
func (*GetLinksRequest) Descriptor() ([]byte, []int) {
	return file_docs_scrapper_proto_rawDescGZIP(), []int{2}
}

func (x *GetLinksRequest) GetTgChatId() int64 {
	if x != nil {
		return x.TgChatId
	}
	return 0
}

type AddLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TgChatId      int64                  `protobuf:"varint,1,opt,name=tg_chat_id,json=tgChatId,proto3" json:"tg_chat_id,omitempty"`
	Link          string                 `protobuf:"bytes,2,opt,name=link,proto3" json:"link,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Filters       []string               `protobuf:"bytes,4,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddLinkRequest) Reset() {
	*x = AddLinkRequest{}
	mi := &file_docs_scrapper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLinkRequest) ProtoMessage() {}

func (x *AddLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_scrapper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLinkRequest.ProtoReflect.Descriptor instead.
func (*AddLinkRequest) Descriptor() ([]byte, []int) {
	return file_docs_scrapper_proto_rawDescGZIP(), []int{3}
}

func (x *AddLinkRequest) GetTgChatId() int64 {
	if x != nil {
		return x.TgChatId
	}
	return 0
}

func (x *AddLinkRequest) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *AddLinkRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *AddLinkRequest) GetFilters() []string {
	if x != nil {
		return x.Filters
	}
	return nil
}

type RemoveLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TgChatId      int64                  `protobuf:"varint,1,opt,name=tg_chat_id,json=tgChatId,proto3" json:"tg_chat_id,omitempty"`
	Link          string                 `protobuf:"bytes,2,opt,name=link,proto3" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveLinkRequest) Reset() {
	*x = RemoveLinkRequest{}
	mi := &file_docs_scrapper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveLinkRequest) ProtoMessage() {}

func (x *RemoveLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_scrapper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveLinkRequest.ProtoReflect.Descriptor instead.
func (*RemoveLinkRequest) Descriptor() ([]byte, []int) {
	return file_docs_scrapper_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveLinkRequest) GetTgChatId() int64 {
	if x != nil {
		return x.TgChatId
	}
	return 0
}

func (x *RemoveLinkRequest) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

type LinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Filters       []string               `protobuf:"bytes,4,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkResponse) Reset() {
	*x = LinkResponse{}
	mi := &file_docs_scrapper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkResponse) ProtoMessage() {}

func (x *LinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_scrapper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkResponse.ProtoReflect.Descriptor instead.
func (*LinkResponse) Descriptor() ([]byte, []int) {
	return file_docs_scrapper_proto_rawDescGZIP(), []int{5}
}

func (x *LinkResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LinkResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *LinkResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *LinkResponse) GetFilters() []string {
	if x != nil {
		return x.Filters
	}
	return nil
}

type ListLinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Links         []*LinkResponse        `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLinksResponse) Reset() {
	*x = ListLinksResponse{}
	mi := &file_docs_scrapper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLinksResponse) ProtoMessage() {}

func (x *ListLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_scrapper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLinksResponse.ProtoReflect.Descriptor instead.
func (*ListLinksResponse) Descriptor() ([]byte, []int) {
	return file_docs_scrapper_proto_rawDescGZIP(), []int{6}
}

func (x *ListLinksResponse) GetLinks() []*LinkResponse {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *ListLinksResponse) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_docs_scrapper_proto protoreflect.FileDescriptor

const file_docs_scrapper_proto_rawDesc = "" +
	"\n" +
	"\x13docs/scrapper.proto\x12\bscrapper\x1a\x1bgoogle/protobuf/empty.proto\"%\n" +
	"\x13RegisterChatRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"#\n" +
	"\x11DeleteChatRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"/\n" +
	"\x0fGetLinksRequest\x12\x1c\n" +
	"\n" +
	"tg_chat_id\x18\x01 \x01(\x03R\btgChatId\"p\n" +
	"\x0eAddLinkRequest\x12\x1c\n" +
	"\n" +
	"tg_chat_id\x18\x01 \x01(\x03R\btgChatId\x12\x12\n" +
	"\x04link\x18\x02 \x01(\tR\x04link\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12\x18\n" +
	"\afilters\x18\x04 \x03(\tR\afilters\"E\n" +
	"\x11RemoveLinkRequest\x12\x1c\n" +
	"\n" +
	"tg_chat_id\x18\x01 \x01(\x03R\btgChatId\x12\x12\n" +
	"\x04link\x18\x02 \x01(\tR\x04link\"^\n" +
	"\fLinkResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12\x18\n" +
	"\afilters\x18\x04 \x03(\tR\afilters\"U\n" +
	"\x11ListLinksResponse\x12,\n" +
	"\x05links\x18\x01 \x03(\v2\x16.scrapper.LinkResponseR\x05links\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size2\xdf\x02\n" +
	"\x0fScrapperService\x12E\n" +
	"\fRegisterChat\x12\x1d.scrapper.RegisterChatRequest\x1a\x16.google.protobuf.Empty\x12A\n" +
	"\n" +
	"DeleteChat\x12\x1b.scrapper.DeleteChatRequest\x1a\x16.google.protobuf.Empty\x12B\n" +
	"\bGetLinks\x12\x19.scrapper.GetLinksRequest\x1a\x1b.scrapper.ListLinksResponse\x12;\n" +
	"\aAddLink\x12\x18.scrapper.AddLinkRequest\x1a\x16.scrapper.LinkResponse\x12A\n" +
	"\n" +
	"RemoveLink\x12\x1b.scrapper.RemoveLinkRequest\x1a\x16.scrapper.LinkResponseB[ZYgitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/pkg/api/scrapperb\x06proto3"

var (
	file_docs_scrapper_proto_rawDescOnce sync.Once
	file_docs_scrapper_proto_rawDescData []byte
)

func file_docs_scrapper_proto_rawDescGZIP() []byte {
	file_docs_scrapper_proto_rawDescOnce.Do(func() {
		file_docs_scrapper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_docs_scrapper_proto_rawDesc), len(file_docs_scrapper_proto_rawDesc)))
	})
	return file_docs_scrapper_proto_rawDescData
}

var file_docs_scrapper_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_docs_scrapper_proto_goTypes = []any{
	(*RegisterChatRequest)(nil), // 0: scrapper.RegisterChatRequest
	(*DeleteChatRequest)(nil),   // 1: scrapper.DeleteChatRequest
	(*GetLinksRequest)(nil),     // 2: scrapper.GetLinksRequest
	(*AddLinkRequest)(nil),      // 3: scrapper.AddLinkRequest
	(*RemoveLinkRequest)(nil),   // 4: scrapper.RemoveLinkRequest
	(*LinkResponse)(nil),        // 5: scrapper.LinkResponse
	(*ListLinksResponse)(nil),   // 6: scrapper.ListLinksResponse
	(*emptypb.Empty)(nil),       // 7: google.protobuf.Empty
}
var file_docs_scrapper_proto_depIdxs = []int32{
	5, // 0: scrapper.ListLinksResponse.links:type_name -> scrapper.LinkResponse
	0, // 1: scrapper.ScrapperService.RegisterChat:input_type -> scrapper.RegisterChatRequest
	1, // 2: scrapper.ScrapperService.DeleteChat:input_type -> scrapper.DeleteChatRequest
	2, // 3: scrapper.ScrapperService.GetLinks:input_type -> scrapper.GetLinksRequest
	3, // 4: scrapper.ScrapperService.AddLink:input_type -> scrapper.AddLinkRequest
	4, // 5: scrapper.ScrapperService.RemoveLink:input_type -> scrapper.RemoveLinkRequest
	7, // 6: scrapper.ScrapperService.RegisterChat:output_type -> google.protobuf.Empty
	7, // 7: scrapper.ScrapperService.DeleteChat:output_type -> google.protobuf.Empty
	6, // 8: scrapper.ScrapperService.GetLinks:output_type -> scrapper.ListLinksResponse
	5, // 9: scrapper.ScrapperService.AddLink:output_type -> scrapper.LinkResponse
	5, // 10: scrapper.ScrapperService.RemoveLink:output_type -> scrapper.LinkResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_docs_scrapper_proto_init() }
func file_docs_scrapper_proto_init() {
	if File_docs_scrapper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_docs_scrapper_proto_rawDesc), len(file_docs_scrapper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_docs_scrapper_proto_goTypes,
		DependencyIndexes: file_docs_scrapper_proto_depIdxs,
		MessageInfos:      file_docs_scrapper_proto_msgTypes,
	}.Build()
	File_docs_scrapper_proto = out.File
	file_docs_scrapper_proto_goTypes = nil
	file_docs_scrapper_proto_depIdxs = nil
}
