// Code generated by MockGen. DO NOT EDIT.
// Source: update_event.go
//
// Generated by this command:
//
//	mockgen -source=update_event.go -destination=../mocks/mock_domain_link_fetcher.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/internal/scrapper/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockUpdateEvent is a mock of UpdateEvent interface.
type MockUpdateEvent struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateEventMockRecorder
	isgomock struct{}
}

// MockUpdateEventMockRecorder is the mock recorder for MockUpdateEvent.
type MockUpdateEventMockRecorder struct {
	mock *MockUpdateEvent
}

// NewMockUpdateEvent creates a new mock instance.
func NewMockUpdateEvent(ctrl *gomock.Controller) *MockUpdateEvent {
	mock := &MockUpdateEvent{ctrl: ctrl}
	mock.recorder = &MockUpdateEventMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateEvent) EXPECT() *MockUpdateEventMockRecorder {
	return m.recorder
}

// Description mocks base method.
func (m *MockUpdateEvent) Description() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Description")
	ret0, _ := ret[0].(string)
	return ret0
}

// Description indicates an expected call of Description.
func (mr *MockUpdateEventMockRecorder) Description() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Description", reflect.TypeOf((*MockUpdateEvent)(nil).Description))
}

// Preview mocks base method.
func (m *MockUpdateEvent) Preview() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Preview")
	ret0, _ := ret[0].(string)
	return ret0
}

// Preview indicates an expected call of Preview.
func (mr *MockUpdateEventMockRecorder) Preview() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Preview", reflect.TypeOf((*MockUpdateEvent)(nil).Preview))
}

// UpdatedAt mocks base method.
func (m *MockUpdateEvent) UpdatedAt() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatedAt")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// UpdatedAt indicates an expected call of UpdatedAt.
func (mr *MockUpdateEventMockRecorder) UpdatedAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatedAt", reflect.TypeOf((*MockUpdateEvent)(nil).UpdatedAt))
}

// MockLinkFetcher is a mock of LinkFetcher interface.
type MockLinkFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockLinkFetcherMockRecorder
	isgomock struct{}
}

// MockLinkFetcherMockRecorder is the mock recorder for MockLinkFetcher.
type MockLinkFetcherMockRecorder struct {
	mock *MockLinkFetcher
}

// NewMockLinkFetcher creates a new mock instance.
func NewMockLinkFetcher(ctrl *gomock.Controller) *MockLinkFetcher {
	mock := &MockLinkFetcher{ctrl: ctrl}
	mock.recorder = &MockLinkFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkFetcher) EXPECT() *MockLinkFetcherMockRecorder {
	return m.recorder
}

// CanHandle mocks base method.
func (m *MockLinkFetcher) CanHandle(url string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanHandle", url)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CanHandle indicates an expected call of CanHandle.
func (mr *MockLinkFetcherMockRecorder) CanHandle(url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanHandle", reflect.TypeOf((*MockLinkFetcher)(nil).CanHandle), url)
}

// Fetch mocks base method.
func (m *MockLinkFetcher) Fetch(ctx context.Context, url string, since time.Time) ([]domain.UpdateEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch", ctx, url, since)
	ret0, _ := ret[0].([]domain.UpdateEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fetch indicates an expected call of Fetch.
func (mr *MockLinkFetcherMockRecorder) Fetch(ctx, url, since any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockLinkFetcher)(nil).Fetch), ctx, url, since)
}
