// Code generated by MockGen. DO NOT EDIT.
// Source: subscription.go
//
// Generated by this command:
//
//	mockgen -source=subscription.go -destination=../mocks/mock_domain_subscription.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/internal/scrapper/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockSubscriptionRepository is a mock of SubscriptionRepository interface.
type MockSubscriptionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionRepositoryMockRecorder
	isgomock struct{}
}

// MockSubscriptionRepositoryMockRecorder is the mock recorder for MockSubscriptionRepository.
type MockSubscriptionRepositoryMockRecorder struct {
	mock *MockSubscriptionRepository
}

// NewMockSubscriptionRepository creates a new mock instance.
func NewMockSubscriptionRepository(ctrl *gomock.Controller) *MockSubscriptionRepository {
	mock := &MockSubscriptionRepository{ctrl: ctrl}
	mock.recorder = &MockSubscriptionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionRepository) EXPECT() *MockSubscriptionRepositoryMockRecorder {
	return m.recorder
}

// AddTags mocks base method.
func (m *MockSubscriptionRepository) AddTags(ctx context.Context, linkId, chatId int64, tags []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTags", ctx, linkId, chatId, tags)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTags indicates an expected call of AddTags.
func (mr *MockSubscriptionRepositoryMockRecorder) AddTags(ctx, linkId, chatId, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTags", reflect.TypeOf((*MockSubscriptionRepository)(nil).AddTags), ctx, linkId, chatId, tags)
}

// Delete mocks base method.
func (m *MockSubscriptionRepository) Delete(ctx context.Context, sub domain.Subscription) (domain.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, sub)
	ret0, _ := ret[0].(domain.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockSubscriptionRepositoryMockRecorder) Delete(ctx, sub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSubscriptionRepository)(nil).Delete), ctx, sub)
}

// DeleteTags mocks base method.
func (m *MockSubscriptionRepository) DeleteTags(ctx context.Context, linkId, chatId int64, tags []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTags", ctx, linkId, chatId, tags)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTags indicates an expected call of DeleteTags.
func (mr *MockSubscriptionRepositoryMockRecorder) DeleteTags(ctx, linkId, chatId, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTags", reflect.TypeOf((*MockSubscriptionRepository)(nil).DeleteTags), ctx, linkId, chatId, tags)
}

// Exists mocks base method.
func (m *MockSubscriptionRepository) Exists(ctx context.Context, chatId, linkId int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, chatId, linkId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockSubscriptionRepositoryMockRecorder) Exists(ctx, chatId, linkId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockSubscriptionRepository)(nil).Exists), ctx, chatId, linkId)
}

// GetByChatId mocks base method.
func (m *MockSubscriptionRepository) GetByChatId(ctx context.Context, chatId int64) ([]domain.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByChatId", ctx, chatId)
	ret0, _ := ret[0].([]domain.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByChatId indicates an expected call of GetByChatId.
func (mr *MockSubscriptionRepositoryMockRecorder) GetByChatId(ctx, chatId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByChatId", reflect.TypeOf((*MockSubscriptionRepository)(nil).GetByChatId), ctx, chatId)
}

// GetByLinkId mocks base method.
func (m *MockSubscriptionRepository) GetByLinkId(ctx context.Context, linkId int64) ([]domain.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByLinkId", ctx, linkId)
	ret0, _ := ret[0].([]domain.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByLinkId indicates an expected call of GetByLinkId.
func (mr *MockSubscriptionRepositoryMockRecorder) GetByLinkId(ctx, linkId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByLinkId", reflect.TypeOf((*MockSubscriptionRepository)(nil).GetByLinkId), ctx, linkId)
}

// GetTags mocks base method.
func (m *MockSubscriptionRepository) GetTags(ctx context.Context, linkId, chatId int64) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTags", ctx, linkId, chatId)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTags indicates an expected call of GetTags.
func (mr *MockSubscriptionRepositoryMockRecorder) GetTags(ctx, linkId, chatId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTags", reflect.TypeOf((*MockSubscriptionRepository)(nil).GetTags), ctx, linkId, chatId)
}

// Save mocks base method.
func (m *MockSubscriptionRepository) Save(ctx context.Context, sub domain.Subscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, sub)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockSubscriptionRepositoryMockRecorder) Save(ctx, sub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockSubscriptionRepository)(nil).Save), ctx, sub)
}
