telegram = {
    token = ${APP_TELEGRAM_TOKEN}
    api-url = "https://api.telegram.org/bot"
    timeout = 30 s
}

logger = {
    level = DEBUG
    level = ${?BOT_LOG_LEVEL}
    file = ${?BOT_LOGS_FILE}
}

scrapper-service = {
    url = ${SCRAPPER_URL}
    protocol = "grpc"
    protocol = ${?SCRAPPER_API_PROTOCOL}
}

server = {
    port = ${BOT_API_PORT}
    protocol = "grpc"
    protocol = ${?BOT_API_PROTOCOL}
}

database = {
    url = ${DATABASE_URL}
    access-type = SQL
}