telegram = {
    token = ${APP_TELEGRAM_TOKEN}
    api-url = "https://api.telegram.org/bot"
    timeout = 10 s
}

logger = {
    level = INFO
    level = ${?BOT_LOG_LEVEL}
    file = ${?BOT_LOGS_FILE}
}

scrapper-service = {
    url = ${SCRAPPER_URL}
    protocol = "grpc"
    protocol = ${?SCRAPPER_API_PROTOCOL}
}

database = {
    url = ${DATABASE_URL}
    access-type = SQL
}

kafka = {
    brokers = ["kafka-1:9092", "kafka-2:9092", "kafka-3:9092"]
    topic = "link-updates"
    dlq-topic = "link-updates-dlq"
    consumer-group = "bot-group-1"
    retries = 3
}