// Code generated by MockGen. DO NOT EDIT.
// Source: scrapper.go
//
// Generated by this command:
//
//	mockgen -source=scrapper.go -destination=../mocks/mock_domain_scrapper.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/internal/bot/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockScrapper is a mock of Scrapper interface.
type MockScrapper struct {
	ctrl     *gomock.Controller
	recorder *MockScrapperMockRecorder
	isgomock struct{}
}

// MockScrapperMockRecorder is the mock recorder for MockScrapper.
type MockScrapperMockRecorder struct {
	mock *MockScrapper
}

// NewMockScrapper creates a new mock instance.
func NewMockScrapper(ctrl *gomock.Controller) *MockScrapper {
	mock := &MockScrapper{ctrl: ctrl}
	mock.recorder = &MockScrapperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScrapper) EXPECT() *MockScrapperMockRecorder {
	return m.recorder
}

// AddLink mocks base method.
func (m *MockScrapper) AddLink(ctx context.Context, chatId int64, url string, tags []string) (domain.TrackedLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddLink", ctx, chatId, url, tags)
	ret0, _ := ret[0].(domain.TrackedLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddLink indicates an expected call of AddLink.
func (mr *MockScrapperMockRecorder) AddLink(ctx, chatId, url, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLink", reflect.TypeOf((*MockScrapper)(nil).AddLink), ctx, chatId, url, tags)
}

// DeleteChat mocks base method.
func (m *MockScrapper) DeleteChat(ctx context.Context, chatId int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChat", ctx, chatId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChat indicates an expected call of DeleteChat.
func (mr *MockScrapperMockRecorder) DeleteChat(ctx, chatId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChat", reflect.TypeOf((*MockScrapper)(nil).DeleteChat), ctx, chatId)
}

// GetTrackedLinks mocks base method.
func (m *MockScrapper) GetTrackedLinks(ctx context.Context, chatId int64) ([]domain.TrackedLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrackedLinks", ctx, chatId)
	ret0, _ := ret[0].([]domain.TrackedLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTrackedLinks indicates an expected call of GetTrackedLinks.
func (mr *MockScrapperMockRecorder) GetTrackedLinks(ctx, chatId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrackedLinks", reflect.TypeOf((*MockScrapper)(nil).GetTrackedLinks), ctx, chatId)
}

// RegisterChat mocks base method.
func (m *MockScrapper) RegisterChat(ctx context.Context, chatId int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterChat", ctx, chatId)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterChat indicates an expected call of RegisterChat.
func (mr *MockScrapperMockRecorder) RegisterChat(ctx, chatId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterChat", reflect.TypeOf((*MockScrapper)(nil).RegisterChat), ctx, chatId)
}

// RemoveLink mocks base method.
func (m *MockScrapper) RemoveLink(ctx context.Context, chatId int64, url string) (domain.TrackedLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveLink", ctx, chatId, url)
	ret0, _ := ret[0].(domain.TrackedLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveLink indicates an expected call of RemoveLink.
func (mr *MockScrapperMockRecorder) RemoveLink(ctx, chatId, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveLink", reflect.TypeOf((*MockScrapper)(nil).RemoveLink), ctx, chatId, url)
}
