logger:
  level: INFO

scheduler:
  job-interval: 60s
  job-timeout: 60s

bot-service:
  protocol: grpc
  resilience:
    timeout: 15s
    retry:
      enabled: true
      max-retries: 3
      delay: 100ms
      backoff: true
      max-delay: 15s
    breaker:
      enabled: true
      max-requests: 5
      sliding-window: 1m
      wait-in-open-state: 30s
      minimum-number-of-calls: 5
      failure-rate-threshold: 0.5

server:
  protocol: grpc
  rate-limit:
    enabled: true
    rps: 6
    burst: 3
    ttl: 30s

database:
  migrations-dir-url: file://migrations
  access-type: BUILDER

fetchers:
  preview-limit: 200
  concurrency: 4
  batch: 500
  resilience:
    timeout: 5s
    retry:
      enabled: true
      max-retries: 3
      delay: 50ms
      backoff: true
      max-delay: 10s
    breaker:
      enabled: true
      max-requests: 5
      sliding-window: 1m
      wait-in-open-state: 30s
      minimum-number-of-calls: 5
      failure-rate-threshold: 0.5
kafka:
  enabled: true
  brokers:
    - kafka-1:9092
    - kafka-2:9092
    - kafka-3:9092
  topic: link-updates.raw
  workers:
    count: 1
    interval: 30s
    event-limit: 50
    max-retries: 7
  schema-registry-url: http://schema-registry:8081
  schema-path: ./docs/link_update.avsc

valkey:
  enabled: true
  addresses:
    - valkey-1:6379
    - valkey-2:6379
    - valkey-3:6379
  ttl: 5m
  key-prefix: "scrapper:links:"
  client-side-cache: true
