logger = {
    level = INFO
    level = ${?SCRAPPER_LOG_LEVEL}
    file = ${?SCRAPPER_LOGS_FILE}
}

scheduler = {
    fetch-interval = 5 m
    fetch-timeout = 60 s
}

bot-service = {
    url = ${BOT_URL}
    protocol = "grpc"
    protocol = ${?BOT_API_PROTOCOL}
}

server = {
    port = ${SCRAPPER_API_PORT}
    protocol = "grpc"
    protocol = ${?SCRAPPER_API_PROTOCOL}
}

database = {
    migrations-dir-url = "file://migrations"
    url = ${DATABASE_URL}
    access-type = BUILDER
    access-type = ${?DATABASE_ACCESS_TYPE}
}

fetchers = {
    preview-limit = 200
    timeout = 10 s
    concurrency = 4 
    concurrency = ${?FETCHERS_COUNT}
    stackoverflow-key = ${STACKOVERFLOW_KEY}
    batch = 500
}

use-queue = true
kafka = {
    brokers = ["kafka-1:9092", "kafka-2:9092", "kafka-3:9092"]
    topic = "link-updates"
}