{
  "type": "record",
  "name": "LinkUpdateEvent",
  "namespace": "domain.LinkUpdate",
  "fields": [
    {
      "name": "id",
      "type": "long",
      "doc": "Link ID"
    },
    {
      "name": "url",
      "type": "string",
      "doc": "Link URL"
    },
    {
      "name": "author",
      "type": "string",
      "doc": "Update author"
    },
    {
      "name": "description",
      "type": "string",
      "doc": "Short update description"
    },
    {
      "name": "tgChatIds",
      "type": {
        "type": "array",
        "items": "long"
      },
      "doc": "Telegram chats IDs"
    }
  ]
}